orbit_display/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'orbit_display'

urlpatterns = [
    path('', views.CheckedBodiesView.as_view(), name='welcome_vis'),
    path('plot/<str:objects>/', views.plot_orbits, name='plot'),
]

web_orbital/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('about/', views.AboutPage.as_view(), name='about'),
    path('orbit_display', include('orbit_display.urls'), name='orbit_display'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

orbit_display/models.py
from django.db import models

# Create your models here.


class CelestialBodyType(models.Model):
    group = models.CharField(max_length=64)

    def __str__(self):
        return self.group


class CelestialBody(models.Model):
    name = models.CharField(max_length=64)
    group = models.ForeignKey('CelestialBodyType', related_name='body_type', on_delete=models.CASCADE)
    a = models.FloatField()
    e = models.FloatField()
    i = models.FloatField()
    w = models.FloatField()
    node = models.FloatField()
    tp = models.FloatField()

    def __str__(self):
        return self.name

orbit_display/forms.py
from django import forms
from .models import CelestialBody
from django.forms import CheckboxSelectMultiple
#
BODIES = [obj.name for obj in CelestialBody.objects.all().order_by('a')]
#
#
class CelestialBodiesChecked(forms.Form):
#     def __init__(self, *args, **kwargs):
#
#         super(CelestialBodiesChecked, self).__init__(*args, **kwargs)
#
#         self.fields["name"].widget = CheckboxSelectMultiple()
#         self.fields["name"].queryset = CelestialBody.objects.all().order_by('a')

    bodies = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        choices=BODIES,
    )

    def show_checked(self):
        print(self.cleaned_data)

orbit_display/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView
from orbit_display.models import CelestialBody
from orbit_display.forms import CelestialBodiesChecked

# Create your views here.


# class OrbitVisPage(TemplateView):
#     template_name = 'orbit_home.html'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data()
#         context['planets'] = CelestialBody.objects.order_by('a')
#         return context
#
#
# def calculate_orbits(request):
#     if request.method == 'POST':
#         print()


class CheckedBodiesView(FormView):
    template_name = 'orbit_home.html'
    form_class = CelestialBodiesChecked
    success_url = '/plot/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['planets'] = CelestialBody.objects.order_by('a')
        return context

    def form_valid(self, form):
        form.show_checked()
        return super(CheckedBodiesView, self).form_valid(form)


class PlotView(TemplateView):
    template_name = 'orbit_plot.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['bodies'] = self.kwargs['objects']


def plot_orbits(request, objects):
    res = request.POST.getlist['check']
    return render(request, 'orbit_plot.html', {'result': res})

web_orbital/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = 'index.html'


class AboutPage(TemplateView):
    template_name = 'about.html'

orbit_display/templates/orbit_base.html
{% extends "base.html" %}

<div class="container">
    <div class="col-md-8">
        <h1>Orbit Visualizer</h1>
    </div>
</div>

<div class="container">
    <div class="col-md-8">
        {% block body_block %}{% endblock %}
    </div>
</div>

orbit_display/templates/orbit_home.html
{% extends "orbit_base.html" %}

{% load django_bootstrap5 %}
{% load crispy_forms_tags %}

{% block body_block %}
    <div class="h-100 p-5 bg-light border rounded-3">
        <h1>This is an orbit visualisation page</h1>
        {% if planets %}
            <p>Select celestial bodies to display</p>
        {% else %}
            <p>No planets to display!</p>
        {% endif %}
    </div>

    <hr>
    {% if planets %}
        <div class="h-100 p-5 bg-light border rounded-3">
        <form action="{% url 'orbit_display:plot' objects=planets.objects %}" method="post" class="planetsform">
            {% csrf_token %}
{#            {{ form }}#}
            {% for planet in planets %}
                <input id="check-{{ planet.name }}" name="check-{{ planet.name }}" type="checkbox">
                <label for="check-{{ planet.name }}">{{ planet.name }}</label>
                <br>
            {% endfor %}
        <br>
        <button type="submit" class="btn btn-primary">Plot</button>
        </form>
        </div>
    {% endif %}

{% endblock %}

orbit_display/templates/orbit_plot.html
{% extends "orbit_base.html" %}

{% block body_block %}
    <h1>{{ result }}</h1>
{% endblock %}

templates/about.html
{% extends "base.html" %}

{% block body_block %}

<div class="h-100 p-5 bg-light border rounded-3">
    <h1>About Us</h1><br>
    <article class="about-text article-text">
        Hello! This is "About us" text
    </article>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Orbital visualisation</title>

    <!-- BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <!-- MY CSS -->
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
</head>
<body>
<div class="container">
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'orbit_display:welcome_vis' %}">ORBITER</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<hr>
<br>

<div class="container">
    <div class="col-md-8">
        {% block body_block %}{% endblock %}
    </div>
</div>

</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block body_block %}

<div class="h-100 p-5 bg-light border rounded-3">
    <article class="welcome-text article-text">
        <h1>Welcome to Orbiter project!</h1><br>
        <p>Welcome text TODO</p>
    </article>
</div>

{% endblock %}